name: obs_blade
description: Control your OBS instance and manage your stream and recording - live!
# Major.Minor.Patch+YYYYMMDD(XX) - XX = incrementing build (resets with new date)
version: 3.2.0+2023012002

publish_to: 'none'

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # CUSTOM
  # Language stuff
  intl: ^0.18.0

  # Get project meta info
  package_info_plus: ^3.0.2

  # Webview
  # flutter_inappwebview: ^5.4.3+7
  webview_flutter: ^4.0.1

  # State Management and DI
  get_it: ^7.2.0
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  path: ^1.8.1

  # Network stuff
  connectivity_plus: ^3.0.2
  web_socket_channel: ^2.2.0

  # Security
  crypto: ^3.0.2

  # Local persistance stuff
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # To enable unique identifiable objects (models)
  uuid: ^3.0.7

  # Enable launching stuff based on URL scheme (Twitter, Browser etc.)
  url_launcher: ^6.1.7

  # Enable keeping the device active
  wakelock: ^0.6.2

  # Initiate native share sheet
  share_plus: ^6.3.0

  # Add custom images
  image_picker: ^0.8.6

  # Get various path related directories on host OS
  path_provider: ^2.0.11

  # Enable and manage in-app purchases
  in_app_purchase: ^3.1.1

  # QR Scanner for quick connect feature
  qr_code_scanner: ^1.0.1

  # Fancy done layout stuff
  modal_bottom_sheet:
    git:
      url: https://github.com/Kounex/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  # fl_chart: ^0.35.0
  fl_chart: ^0.55.2
  smooth_page_indicator: ^1.0.0+2
  keyboard_actions: ^4.1.0
  expandable: ^5.0.1
  flutter_slidable: ^2.0.0
  confetti: ^0.7.0

  # Additional dependencies for packages
  xml: ^6.1.0

  # Splashscreen ios and android
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

  # Codegen
  build_resolvers: ^2.1.0
  build_runner: ^2.3.2
  hive_generator: ^2.0.0
  mobx_codegen: ^2.1.1

  # App icons
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/icons/app/app_logo.png'
  adaptive_icon_background: '#141C24'
  adaptive_icon_foreground: 'assets/icons/app/app_logo_adaptive.png'

flutter_native_splash:
  image: assets/icons/app/splash.png
  color: '#101823'
  color_dark: '#101823'

  android_12:
    image: assets/icons/app/splash.png
    icon_background_color: '#101823'
    image_dark: assets/icons/app/splash.png
    icon_background_color_dark: '#101823'

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app/
    - assets/images/
    - assets/images/intro/

  fonts:
    - family: JamIcons
      fonts:
        - asset: assets/fonts/JamIcons.ttf
